// <auto-generated />
using CRUDapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDapp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CRUDapp.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Text = "Just some text1",
                            UserName = "User1"
                        },
                        new
                        {
                            PostId = 2,
                            Text = "Just some text2",
                            UserName = "User2"
                        },
                        new
                        {
                            PostId = 3,
                            Text = "Just some text3",
                            UserName = "User3"
                        },
                        new
                        {
                            PostId = 4,
                            Text = "Just some text4",
                            UserName = "User4"
                        },
                        new
                        {
                            PostId = 5,
                            Text = "Just some text5",
                            UserName = "User5"
                        },
                        new
                        {
                            PostId = 6,
                            Text = "Just some text6",
                            UserName = "User6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
